name: User_CD

on:
  workflow_run:
    workflows:
      - User_CI
    types:
      - completed
    branches:
      - main
      - dev

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: finance-flow1/CI-CD-Templates/.github/workflows/common-cd.yml@main
    with:
      service-name: financeflow-userservice
      helm-chart-key: user-service
      ci-workflow-name: User_CI
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      MANIFEST_REPO: ${{ secrets.MANIFEST_REPO }}
